// 全120種類のマスターカードデータ定義
// N: 64枚, R: 40枚, SR: 10枚, UR: 4枚, SEC: 2枚

const MASTER_CARDS = [
    // --- N (ノーマル) 64枚 : どうぶつ・いきもの ---
    { id: 1, name: "いぬ", rarity: "N", icon: "🐶", power: 10 },
    { id: 2, name: "ねこ", rarity: "N", icon: "🐱", power: 12 },
    { id: 3, name: "ねずみ", rarity: "N", icon: "🐭", power: 14 },
    { id: 4, name: "はむすたー", rarity: "N", icon: "🐹", power: 15 },
    { id: 5, name: "うさぎ", rarity: "N", icon: "🐰", power: 16 },
    { id: 6, name: "きつね", rarity: "N", icon: "🦊", power: 18 },
    { id: 7, name: "くま", rarity: "N", icon: "🐻", power: 25 },
    { id: 8, name: "ぱんだ", rarity: "N", icon: "🐼", power: 20 },
    { id: 9, name: "こあら", rarity: "N", icon: "🐨", power: 18 },
    { id: 10, name: "とら", rarity: "N", icon: "🐯", power: 28 },
    { id: 11, name: "らいおん", rarity: "N", icon: "🦁", power: 30 },
    { id: 12, name: "うし", rarity: "N", icon: "🐮", power: 24 },
    { id: 13, name: "ぶた", rarity: "N", icon: "🐷", power: 18 },
    { id: 14, name: "かえる", rarity: "N", icon: "🐸", power: 15 },
    { id: 15, name: "さる", rarity: "N", icon: "🐵", power: 22 },
    { id: 16, name: "にわとり", rarity: "N", icon: "🐔", power: 14 },
    { id: 17, name: "ぺんぎん", rarity: "N", icon: "🐧", power: 18 },
    { id: 18, name: "ことり", rarity: "N", icon: "🐦", power: 12 },
    { id: 19, name: "ひよこ", rarity: "N", icon: "🐤", power: 8 },
    { id: 20, name: "あひる", rarity: "N", icon: "🦆", power: 14 },
    { id: 21, name: "わし", rarity: "N", icon: "🦅", power: 25 },
    { id: 22, name: "ふくろう", rarity: "N", icon: "🦉", power: 20 },
    { id: 23, name: "こうもり", rarity: "N", icon: "🦇", power: 15 },
    { id: 24, name: "おおかみ", rarity: "N", icon: "🐺", power: 26 },
    { id: 25, name: "いのしし", rarity: "N", icon: "🐗", power: 27 },
    { id: 26, name: "うま", rarity: "N", icon: "🐴", power: 24 },
    { id: 27, name: "ゆにこーん", rarity: "N", icon: "🦄", power: 35 },
    { id: 28, name: "はち", rarity: "N", icon: "🐝", power: 12 },
    { id: 29, name: "いもむし", rarity: "N", icon: "🐛", power: 5 },
    { id: 30, name: "ちょうちょ", rarity: "N", icon: "🦋", power: 8 },
    { id: 31, name: "かたつむり", rarity: "N", icon: "🐌", power: 10 },
    { id: 32, name: "てんとう虫", rarity: "N", icon: "🐞", power: 10 },
    { id: 33, name: "あり", rarity: "N", icon: "🐜", power: 12 },
    { id: 34, name: "か", rarity: "N", icon: "🦟", power: 5 },
    { id: 35, name: "こおろぎ", rarity: "N", icon: "🦗", power: 11 },
    { id: 36, name: "くも", rarity: "N", icon: "🕷", power: 18 },
    { id: 37, name: "さそり", rarity: "N", icon: "🦂", power: 25 },
    { id: 38, name: "かめ", rarity: "N", icon: "🐢", power: 22 },
    { id: 39, name: "へび", rarity: "N", icon: "🐍", power: 20 },
    { id: 40, name: "とかげ", rarity: "N", icon: "🦎", power: 14 },
    { id: 41, name: "ティラノ", rarity: "N", icon: "🦖", power: 45 },
    { id: 42, name: "ブラキオ", rarity: "N", icon: "🦕", power: 40 },
    { id: 43, name: "たこ", rarity: "N", icon: "🐙", power: 18 },
    { id: 44, name: "いか", rarity: "N", icon: "🦑", power: 18 },
    { id: 45, name: "えび", rarity: "N", icon: "🦐", power: 16 },
    { id: 46, name: "ロブスター", rarity: "N", icon: "🦞", power: 22 },
    { id: 47, name: "かに", rarity: "N", icon: "🦀", power: 20 },
    { id: 48, name: "ふぐ", rarity: "N", icon: "🐡", power: 25 },
    { id: 49, name: "熱帯魚", rarity: "N", icon: "🐠", power: 10 },
    { id: 50, name: "さかな", rarity: "N", icon: "🐟", power: 12 },
    { id: 51, name: "いるか", rarity: "N", icon: "🐬", power: 28 },
    { id: 52, name: "くじら", rarity: "N", icon: "🐳", power: 40 },
    { id: 53, name: "しろながす", rarity: "N", icon: "🐋", power: 42 },
    { id: 54, name: "さめ", rarity: "N", icon: "🦈", power: 38 },
    { id: 55, name: "わに", rarity: "N", icon: "🐊", power: 33 },
    { id: 56, name: "とら", rarity: "N", icon: "🐅", power: 29 },
    { id: 57, name: "ひょう", rarity: "N", icon: "🐆", power: 27 },
    { id: 58, name: "しまうま", rarity: "N", icon: "🦓", power: 23 },
    { id: 59, name: "ごりら", rarity: "N", icon: "🦍", power: 34 },
    { id: 60, name: "オランウータン", rarity: "N", icon: "🦧", power: 30 },
    { id: 61, name: "ぞう", rarity: "N", icon: "🐘", power: 36 },
    { id: 62, name: "かば", rarity: "N", icon: "🦛", power: 32 },
    { id: 63, name: "さい", rarity: "N", icon: "🦏", power: 31 },
    { id: 64, name: "らくだ", rarity: "N", icon: "🐪", power: 28 },

    // --- R (レア) 40枚 : たべもの・くだもの ---
    { id: 65, name: "りんご", rarity: "R", icon: "🍎", power: 50 },
    { id: 66, name: "洋なし", rarity: "R", icon: "🍐", power: 51 },
    { id: 67, name: "みかん", rarity: "R", icon: "🍊", power: 52 },
    { id: 68, name: "レモン", rarity: "R", icon: "🍋", power: 55 },
    { id: 69, name: "バナナ", rarity: "R", icon: "🍌", power: 58 },
    { id: 70, name: "すいか", rarity: "R", icon: "🍉", power: 65 },
    { id: 71, name: "ぶどう", rarity: "R", icon: "🍇", power: 54 },
    { id: 72, name: "いちご", rarity: "R", icon: "🍓", power: 56 },
    { id: 73, name: "メロン", rarity: "R", icon: "🍈", power: 70 },
    { id: 74, name: "さくらんぼ", rarity: "R", icon: "🍒", power: 53 },
    { id: 75, name: "もも", rarity: "R", icon: "🍑", power: 62 },
    { id: 76, name: "マンゴー", rarity: "R", icon: "🥭", power: 66 },
    { id: 77, name: "パイナップル", rarity: "R", icon: "🍍", power: 64 },
    { id: 78, name: "ココナッツ", rarity: "R", icon: "🥥", power: 68 },
    { id: 79, name: "キウイ", rarity: "R", icon: "🥝", power: 52 },
    { id: 80, name: "トマト", rarity: "R", icon: "🍅", power: 50 },
    { id: 81, name: "なす", rarity: "R", icon: "🍆", power: 48 },
    { id: 82, name: "アボカド", rarity: "R", icon: "🥑", power: 55 },
    { id: 83, name: "ブロッコリー", rarity: "R", icon: "🥦", power: 60 },
    { id: 84, name: "レタス", rarity: "R", icon: "🥬", power: 45 },
    { id: 85, name: "きゅうり", rarity: "R", icon: "🥒", power: 47 },
    { id: 86, name: "とうがらし", rarity: "R", icon: "🌶", power: 75 },
    { id: 87, name: "とうもろこし", rarity: "R", icon: "🌽", power: 55 },
    { id: 88, name: "にんじん", rarity: "R", icon: "🥕", power: 50 },
    { id: 89, name: "じゃがいも", rarity: "R", icon: "🥔", power: 52 },
    { id: 90, name: "さつまいも", rarity: "R", icon: "🍠", power: 54 },
    { id: 91, name: "クロワッサン", rarity: "R", icon: "🥐", power: 60 },
    { id: 92, name: "しょくぱん", rarity: "R", icon: "🍞", power: 58 },
    { id: 93, name: "フランスパン", rarity: "R", icon: "🥖", power: 62 },
    { id: 94, name: "プレッツェル", rarity: "R", icon: "🥨", power: 55 },
    { id: 95, name: "チーズ", rarity: "R", icon: "🧀", power: 65 },
    { id: 96, name: "たまご", rarity: "R", icon: "🥚", power: 50 },
    { id: 97, name: "めだまやき", rarity: "R", icon: "🍳", power: 55 },
    { id: 98, name: "パンケーキ", rarity: "R", icon: "🥞", power: 68 },
    { id: 99, name: "ベーコン", rarity: "R", icon: "🥓", power: 70 },
    { id: 100, name: "ステーキ", rarity: "R", icon: "🥩", power: 85 },
    { id: 101, name: "チキン", rarity: "R", icon: "🍗", power: 80 },
    { id: 102, name: "おにく", rarity: "R", icon: "🍖", power: 82 },
    { id: 103, name: "ホットドッグ", rarity: "R", icon: "🌭", power: 72 },
    { id: 104, name: "ハンバーガー", rarity: "R", icon: "🍔", power: 78 },

    // --- SR (スーパーレア) 10枚 : のりもの ---
    { id: 105, name: "スポーツカー", rarity: "SR", icon: "🚗", power: 120 },
    { id: 106, name: "タクシー", rarity: "SR", icon: "🚕", power: 105 },
    { id: 107, name: "ジープ", rarity: "SR", icon: "🚙", power: 115 },
    { id: 108, name: "バス", rarity: "SR", icon: "🚌", power: 130 },
    { id: 109, name: "トロリーバス", rarity: "SR", icon: "🚎", power: 110 },
    { id: 110, name: "レーシングカー", rarity: "SR", icon: "🏎", power: 140 },
    { id: 111, name: "パトカー", rarity: "SR", icon: "🚓", power: 125 },
    { id: 112, name: "救急車", rarity: "SR", icon: "🚑", power: 125 },
    { id: 113, name: "消防車", rarity: "SR", icon: "🚒", power: 135 },
    { id: 114, name: "キャンピングカー", rarity: "SR", icon: "🚐", power: 118 },

    // --- UR (ウルトラレア) 4枚 : でんせつのアイテム ---
    { id: 115, name: "伝説の剣", rarity: "UR", icon: "⚔️", power: 200 },
    { id: 116, name: "勇者の盾", rarity: "UR", icon: "🛡️", power: 210 },
    { id: 117, name: "魔法の杖", rarity: "UR", icon: "🪄", power: 220 },
    { id: 118, name: "予言の水晶", rarity: "UR", icon: "🔮", power: 230 },

    // --- SEC (シークレット) 2枚 : きゅうきょくのお宝 ---
    { id: 119, name: "覇王の王冠", rarity: "SEC", icon: "👑", power: 300 },
    { id: 120, name: "究極の宝石", rarity: "SEC", icon: "💎", power: 999 }
];

// 所持カードの取得（未所持の場合は 0枚スタート `[]` で統一）
function getPlayerCollection() {
    let raw = localStorage.getItem('playerCollection');
    if (raw === null) {
        localStorage.setItem('playerCollection', '[]');
        return [];
    }
    return JSON.parse(raw);
}